# OpenCV

## Import

In [2]:
import numpy as np
import cv2

## Read image

In [3]:
img = cv2.imread('image.webp', 0)
print(img)


[[210 210 210 ... 210 210 210]
 [210 210 210 ... 210 210 210]
 [210 210 210 ... 210 210 210]
 ...
 [210 210 210 ... 210 210 210]
 [210 210 210 ... 210 210 210]
 [210 210 210 ... 210 210 210]]


Different ways of reading images: colored, grayscale, original

In [4]:
# integer representation for image loading

print(f"Grayscale: {cv2.IMREAD_GRAYSCALE}")
print(f"Colored: {cv2.IMREAD_COLOR}")
print(f"Original: {cv2.IMREAD_UNCHANGED}")
# (f"Transparent (background removed containing alpha channel): {cv2.IMREAD_UNCHANGED}")

Grayscale: 0
Colored: 1
Original: -1


In [4]:
print(img.shape)

(1120, 1920)


## Display image

In [5]:
# read image
img = cv2.imread('Introvert-traits.png', -1)

# display
cv2.imshow("Image", img)

# wait for 5000 ms --> 5s
cv2.waitKey(0)

# press any key to remove the image from screen

# destroy the windows
cv2.destroyAllWindows()

## Check image properties

In [6]:
img.dtype, img.shape

(dtype('uint8'), (2048, 2732, 3))

## Access and modify pixel values (essentially x,y values of a matrix)

In [7]:
# make a copy of original image
new_img = img.copy()

# see pixel value at this coordinate position
new_img[200, 500]  # [y, x]

array([240, 244, 245], dtype=uint8)

In [8]:
# modify the ROI
new_img[200:100, 400:200] = 0  


cv2.imshow("New image", new_img)
cv2.waitKey(20000)
cv2.destroyAllWindows()

In [4]:
# helper function 1 to show image
def show_img(img, delay=0):
    """
    displays an image using OpenCV

    Args:
        img (image): image
        delay (int, optional): time in milliseconds to display the image. Defaults to 0.
    """
    cv2.imshow("Image", img)
    cv2.waitKey(delay = delay)
    cv2.destroyAllWindows()


## Resize image

aspect ratio not maintained 👇

In [10]:
# resized_img = cv2.resize(img, (500, 500))  # 1. Resizing to fixed 500 x 500 (width, height)
resized_img = cv2.resize(img, (0,0), fx = .125, fy = .235)
show_img(resized_img, 5000)  

aspect ratio maintained 👇

In [11]:
# read colored image
img = cv2.imread('image.webp', 1)

# get the height, width, channel
height, width, channel = img.shape

# compute ratio for the new height taking into account the 300px width of image
ratio = 300.0/width

# get the new height
new_height = int(height * ratio)

# resize with new values
resized_img = cv2.resize(img, (300, new_height))

# display resized img
show_img(resized_img)

- Creating helper functions for repeated code is very important. DRY!
- Writing good docstrings is essential!

In [47]:
# helper function 2 to resize image while maintaing aspect ratio
def resize_img(img, w, delay=0, show=False):  
    """
    A function to resize an image while preserving the aspect ratio. Pass an image and the width. The new height will be calculated accordingly.

    Args:
        img (int): Image to be resized
        w (int): New width of the image
        delay (int, optional): Time in milliseconds for the image to be displayed. Defaults to 0.
        show (bool, optional): Displays the image if set to True. Defaults to False.
    """
    img = cv2.imread(img, 1)
    height, width, channel = img.shape
    ratio = w/width
    h = int(height * ratio)
    resized_img = cv2.resize(img, (w,h))

    if show:
        show_img(resized_img, delay=delay)

    return resized_img


In [38]:
help(resize_img)

Help on function resize_img in module __main__:

resize_img(img, w, delay=0, show=False)
    A function to resize an image while preserving the aspect ratio. Pass an image and the width. The new height will be calculated accordingly.

    Args:
        img (int): Image to be resized
        w (int): New width of the image
        delay (int, optional): Time in milliseconds for the image to be displayed. Defaults to 0.
        show (bool, optional): Displays the image if set to True. Defaults to False.



In [14]:
resize_img('Introvert-traits.png', 500, 5000)

## Translate image

In [15]:
img = cv2.imread('Introvert-traits.png', 1)
rows, cols, channels = img.shape

# dials to control translation along x and y axes
tx = 20.
ty = 12.

# construct the translation matrix, must be float 32
M = np.array([
    [1., 0., tx],
    [0., 1., ty]
])

# apply warpAffine 
translated = cv2.warpAffine(img, M, (cols, rows))

show_img(translated)

## Rotate image

In [23]:
angle = 50

# get rows and cols 
width, height = img.shape[:2]
centre = (height/2, width/2)

# rotating image from centre as anchor with 45 degree at the same scale
rotation_matrix = cv2.getRotationMatrix2D(centre, angle, 1)

# apply the transformation
rotated = cv2.warpAffine(img, rotation_matrix, (height, width), borderMode=0)  # borderMode fills the background of rotated image

# display
show_img(rotated)

In [19]:
cv2.BORDER_CONSTANT

0

## Draw shapes on image (Annotate)

### Line

In [48]:
resized = resize_img('image.webp', 700, show=True)

In [49]:
resized.shape

(408, 700, 3)

In [56]:
line = cv2.line(resized, (100,50), (200,400), (0,255,255), 2)
show_img(line)

### Circle

In [ ]:
circle = cv2.circle(resized, (400,200), 90, (0,0,255), 4)  # replace thickness with -1 to fill
show_img(circle)

### Rectangle

In [ ]:
rect = cv2.rectangle(resized, (100,299), (200, 120), 1, -1)  # replace thickness with -1 to fill
show_img(rect)

### Text

In [ ]:
text = cv2.putText(resized, "Hello", (180, 230), 2, 1, 3)
show_img(text)

## Crop image
A quick note on accessing pixel values as (y,x) instead of (x,y) 👇

In math coordinate system, we access a point through (x,y) coordinates. 

But in OpenCV, we are dealing with images, which are matrices. Matrices are made of rows and columns. 

Just like in Numpy, a shape of (2,3) means 2 rows, 3 columns.

Similarly, image[50, 100] means:

**Go to the 50th row (height) → that’s the vertical axis → y**

**Then the 100th column (width) → horizontal axis → x**

That’s why it feels "backwards" — because images are matrices, not coordinate plots.

In [102]:
image = cv2.imread('image.webp')

# grab the ROI
cropped = image[1000:1400, 1200:1900]  # y,x --> rows, cols
show_img(cropped)

## Image smoothing/blurring

In [115]:
blurred = cv2.GaussianBlur(image, (5,5), 60)
show_img(blurred)

## Color conversion

In [120]:
gray_converted = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
show_img(gray_converted)

## Image thresholding
Image should be in grayscale 

just change the flags!

In [132]:
ret, binary = cv2.threshold(gray_converted, 150, 255, cv2.THRESH_BINARY)
show_img(binary)

In [131]:
ret, binary_inverse = cv2.threshold(gray_converted, 150, 255, cv2.THRESH_BINARY_INV)
show_img(binary_inverse)

In [134]:
ret, binary_inverse = cv2.threshold(gray_converted, 100, 255, cv2.THRESH_TRUNC)
show_img(binary_inverse)

## Edge Detection

In [140]:
edge = cv2.Canny(image, 200, 50)
show_img(edge)

## Contours

1. convert image to grayscale
2. make an edge map through binary inverse theshold or simple edge detection. but it requires the background to be black and foreground to be white
3. find the contours
4. draw them on the image

In [141]:
gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
_, edge_map = cv2.threshold(gray, 200, 255, cv2.THRESH_BINARY_INV)
contours, _ = cv2.findContours(edge_map, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
cv2.drawContours(image, contours, -1, (255,0,0), 4)
show_img(image)

## Morphological operations
1. Erosion
2. Dilation
3. Opening
4. Closing

Image must be in grayscale

### Erosion 
Thins out the image. Makes the white pixel areas thinner



Why ones in kernel? 

You multiply kernel values by pixel values. If it is all 0, the output will be 0. If it is different than 1, the output is magnified by the value you put in kernel. It is 1, to keep the pixel value as is,

In [ ]:
# read image in grayscale
image = cv2.imread('image.webp', 0)

# make a 7x7 kernel of ones

kernel = np.ones(7, np.uint8)

# apply erosion with 2 iterations
eroded_img = cv2.erode(image, kernel, iterations = 2)

# show
cv2.imshow("eroded_img", eroded_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Dilation
Dilates the white pixel area

In [ ]:
# read image in grayscale
image = cv2.imread('image.webp', 0)

# make a 7x7 kernel of ones

kernel = np.ones(7, np.uint8)

# apply dilation with 2 iterations
eroded_img = cv2.dilate(image, kernel, iterations = 2)

# show
cv2.imshow("eroded_img", eroded_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Using live webcam feed

In [2]:
# initialize VideoCapture object
cap = cv2.VideoCapture(0)

# initialize a loop and read video frame by frame
while(True):
    ret, frame = cap.read()  # ret gets False/True if all frames are read correctly or not respectively

    # if a frame is not read correctly, exit
    if not ret:
        break

    # perform any image processing operations
    gray = cv2.cvtColor(frame, cv2.COLOR_RGB2GRAY)

    cv2.imshow("frame", gray)

    # wait for 1 ms, before showing next frame
    # if user presses 'q', exit
    if cv2.waitKey(1) == ord('q'):
        break

# release the camera
cap.release()

cv2.destroyAllWindows()

## Face detection using Haar Cascade

In [7]:
image = cv2.imread('face.png')

# initializing the haar classifier with the face detector model
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

# perform detection
detected_face = face_cascade.detectMultiScale(image, 1.3, 5)

# loop through each face and draw rectangel on face coordinates
for (x,y,w,h) in detected_face:
    cv2.rectangle(image, (x,y), (x+w, y+h), (0,255,0), 4)
    cv2.putText(image, "Face", (x,y+h+15), cv2.FONT_HERSHEY_COMPLEX, 0.5, (255,0,0), 1, cv2.LINE_AA)

# display
show_img(image)